

server:
  port: 8084

spring:
  application:
    name: api_gateway_service

zuul:
  routes:
    weather-forecast:
      path: /myapp/api/weather-forecast/**
      url: http://localhost:8081/myapp
    weather-data:
      url: http://localhost:8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/