

server:
  port: 8084

spring:
  application:
    name: api_gateway_service

zuul:
  routes:
    weather-forecast:
      url: http://localhost:8081

    weather-data:
      url: http://localhost:8082